name: "git-clang-format action"
description: "run clang-format on your code"
author: "kevmo314"
branding:
  icon: align-center
  color: yellow
inputs:
  style:
    description: "style passed to clang-format. reads .clang-format file in the repo by default. see clang-format docs for more."
    default: "file"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.style }}
